---
apiVersion: v1
kind: Namespace
metadata:
  name: techdemo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apikube-configmap
  namespace: techdemo
data:
  API_PORT: "8000"
  # CUSTOM_MESSAGE: "Running in default Env."

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apikube
  namespace: techdemo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/xamma/apikube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          # envFrom:
          #   - secretRef: 
          #       name: thumbsnail-secret
          env:
            - name: CUSTOM_MESSAGE
              value: Running in default Env.
          # envFrom:
          #   - configMapRef:
          #       name: apikube-configmap