name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Build images'
        type: choice
        options:
        - buildandpush
  push:
    branches: [ "master" ]

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: xamma/Apikube
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push dockerimage
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/xamma/apikube:latest